// Fast path for loading the demo dataset committed to the repo
// (backend/seed-data/*.json, generated by backend/scripts/seed-demo-full.ts
// — see SEED_DEMO_DATA_PROMPT.md). Wipes the database and inserts the
// committed fixtures directly via the native driver (bypassing Mongoose
// validation/hooks, since the fixtures already contain fully-formed,
// consistent documents with their original _ids preserved) — no external
// API key needed, no business logic re-run, just data. This is what anyone
// cloning the repo should run to get the exact same realistic dataset
// seed-demo-full.ts produced, without regenerating it themselves.
import "dotenv/config";
import fs from "fs";
import path from "path";
import mongoose from "mongoose";
import { User } from "../src/models/User";
import { Ticket } from "../src/models/Ticket";
import { Conversation } from "../src/models/Conversation";
import { Message } from "../src/models/Message";
import { Faq } from "../src/models/Faq";
import { HelpArticle } from "../src/models/HelpArticle";
import { TicketCategory } from "../src/models/TicketCategory";
import { SlaTarget } from "../src/models/SlaTarget";
import { SlaSystemSettings } from "../src/models/SlaSystemSettings";
import { Notification } from "../src/models/Notification";
import { RefreshFamily } from "../src/models/RefreshFamily";

const SEED_DATA_DIR = path.join(__dirname, "..", "seed-data");

// Order matters only for readability of the log output — all wipes happen
// before any insert, so there's no referential-integrity ordering concern.
const FIXTURES = [
  { file: "users.json", model: User },
  { file: "ticketCategories.json", model: TicketCategory },
  { file: "slaTargets.json", model: SlaTarget },
  { file: "slaSystemSettings.json", model: SlaSystemSettings },
  { file: "tickets.json", model: Ticket },
  { file: "conversations.json", model: Conversation },
  { file: "messages.json", model: Message },
  { file: "faqs.json", model: Faq },
  { file: "helpArticles.json", model: HelpArticle },
] as const;

// Reverse of seed-demo-full.ts's `replacer` — {"$oid": "..."} back to an
// ObjectId, {"$date": "..."} back to a Date. JSON.parse's reviver runs
// bottom-up, so by the time it's called on a field whose value is
// `{ $oid: "..." }`, that inner string has already been revived unchanged
// and can be read directly here.
function reviver(_key: string, value: unknown): unknown {
  if (value && typeof value === "object") {
    const v = value as Record<string, unknown>;
    if (typeof v.$oid === "string") return new mongoose.Types.ObjectId(v.$oid);
    if (typeof v.$date === "string") return new Date(v.$date);
  }
  return value;
}

async function main() {
  if (process.env.NODE_ENV === "production") {
    throw new Error("[import-demo-data] refusing to wipe the database with NODE_ENV=production");
  }
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    throw new Error("MONGODB_URI is not set. Copy backend/.env.example to backend/.env and fill it in.");
  }
  if (!fs.existsSync(SEED_DATA_DIR)) {
    throw new Error(
      `${SEED_DATA_DIR} not found. Run "npm run seed:demo-full" first to generate it, or pull the committed fixtures.`
    );
  }

  await mongoose.connect(uri);

  console.log("[import-demo-data] wiping database...");
  await Promise.all([
    User.deleteMany({}),
    Ticket.deleteMany({}),
    Conversation.deleteMany({}),
    Message.deleteMany({}),
    Faq.deleteMany({}),
    HelpArticle.deleteMany({}),
    TicketCategory.deleteMany({}),
    SlaTarget.deleteMany({}),
    SlaSystemSettings.deleteMany({}),
    Notification.deleteMany({}),
    RefreshFamily.deleteMany({}),
  ]);
  await mongoose.connection.collection("counters").deleteMany({});

  for (const { file, model } of FIXTURES) {
    const filePath = path.join(SEED_DATA_DIR, file);
    if (!fs.existsSync(filePath)) {
      console.log(`[import-demo-data] ${file} not found — skipping`);
      continue;
    }
    const docs = JSON.parse(fs.readFileSync(filePath, "utf8"), reviver);
    if (Array.isArray(docs) && docs.length > 0) {
      await model.collection.insertMany(docs);
    }
    console.log(`[import-demo-data] imported ${Array.isArray(docs) ? docs.length : 0} from ${file}`);
  }

  // The membershipNumber/ticketNumber Counter documents aren't part of the
  // fixtures (they're derived, not content) — reseed them from the highest
  // number actually imported so the next NEW ticket/user created by hand
  // continues the sequence instead of colliding with a seeded one.
  const [highestMembership, highestTicket] = await Promise.all([
    User.find({}).sort({ membershipNumber: -1 }).limit(1).select("membershipNumber").lean(),
    Ticket.find({}).sort({ ticketNumber: -1 }).limit(1).select("ticketNumber").lean(),
  ]);
  await mongoose.connection.collection("counters").insertMany(
    [
      highestMembership[0] ? { _id: "membershipNumber", seq: Number(highestMembership[0].membershipNumber) } : null,
      highestTicket[0] ? { _id: "ticketNumber", seq: highestTicket[0].ticketNumber } : null,
    ].filter((doc): doc is { _id: string; seq: number } => doc !== null)
  );

  console.log("[import-demo-data] done.");
  await mongoose.disconnect();
}

main().catch((err) => {
  console.error("[import-demo-data] failed:", err);
  process.exit(1);
});
